before:
  hooks:
    - go mod tidy
    - make clean kernel initfs
checksum:
  disable: true 
snapshot:
  name_template: '{{envOrDefault "VERSION" .ShortCommit}}'
builds:
  - id: default
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: "-X main.Version={{.Version}}"
    main: ./cmd/wanix
  - id: mac
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: "-X main.Version={{.Version}}"
    main: ./cmd/wanix
    hooks:
      post: "codesign --deep --force --verify --verbose --timestamp --options runtime --sign 'Developer ID Application: Jeff Lindsay (4HSU97X8UX)' {{ .Path }}"
archives:
- id: default
  builds:
  - default
  - mac
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{.Os}}_{{.Arch}}'
  format: zip
  wrap_in_directory: false
  files:
    - none*